name: Secret Scanning and Notification

on:
  pull_request:
    branches:
      - main
      - test-secret-branch  # Add the branches you want to monitor

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Send Telegram Notification
        if: failure()  # Only send a message if the secret scan fails
        run: |
          curl -X POST "https://api.telegram.org/bot7357wefwfwfwf276704:AAFlF2d3tq9qj_C9hn4vfSJ5RDJEB9Z8rzk/sendMessage" \
          -d "chat_id=-1002413586935" \
          -d "text=Secret detected in the repository. Please review the changes."
